CREATE TABLE `users` (
` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
` VARCHAR(255) NOT NULL,
` VARCHAR(255) NOT NULL,
` VARCHAR(255) NOT NULL,
` VARCHAR(255) NOT NULL,
` TIMESTAMP NOT NULL DEFAULT current_timestamp,
` TIMESTAMP NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY(`id`)
);


CREATE TABLE `inventory` (
` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
` VARCHAR(255) NOT NULL,
` VARCHAR(255) NOT NULL,
` DECIMAL(10,2) NOT NULL,
` TIMESTAMP NOT NULL DEFAULT current_timestamp,
` TIMESTAMP NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY(`id`)
);


